@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

' === INVISIBLE HELPER OUTSIDE THE PACKAGE ===
Class I #FFFFFF

Package Model as ModelPackage <<Rectangle>> {
  ' === TOP ROW: INTERFACES - FORCE POSITIONING ===
  Class "<<interface>>\nModel" as Model

  Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
  Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs

  ' Force Model in the middle
  ReadOnlyAddressBook -[hidden]right-> Model
  Model -[hidden]right-> ReadOnlyUserPrefs

  ' === SECOND ROW: IMPLEMENTATIONS ===
  Class AddressBook
  Class ModelManager
  Class UserPrefs

  AddressBook -[hidden]right-> ModelManager
  ModelManager -[hidden]right-> UserPrefs

  ' === THIRD ROW: UNIQUE LISTS ===
  Class UniquePersonList
  Class UniqueEventList
  Class UniqueTodoList

  UniquePersonList -[hidden]right-> UniqueEventList
  UniqueEventList -[hidden]right-> UniqueTodoList

  ' === FOURTH ROW: ENTITIES ===
  Class Person
  Class Event
  Class Todo

  Person -[hidden]right-> Event
  Event -[hidden]right-> Todo

  ' === PERSON FIELD CLASSES ===
  Class Name
  Class Phone
  Class Email
  Class Address
  Class Tag

  ' === EVENT FIELD CLASSES ===
  Class EventName
  Class EventAlias

  ' === TODO FIELD CLASSES ===
  Class TodoName
}

' === DASHED REFERENCE FROM OUTSIDE ===
I ..> Model

' === VERTICAL ALIGNMENT ===
ReadOnlyAddressBook -[hidden]down-> AddressBook
Model -[hidden]down-> ModelManager
ReadOnlyUserPrefs -[hidden]down-> UserPrefs
AddressBook -[hidden]down-> UniquePersonList
ModelManager -[hidden]down-> UniqueEventList
UserPrefs -[hidden]down-> UniqueTodoList
UniquePersonList -[hidden]down-> Person
UniqueEventList -[hidden]down-> Event
UniqueTodoList -[hidden]down-> Todo

' === CORE INTERFACE RELATIONSHIPS ===
AddressBook .up.|> ReadOnlyAddressBook
UserPrefs .up.|> ReadOnlyUserPrefs
ModelManager .up.|> Model
Model ..> ReadOnlyAddressBook
Model ..> ReadOnlyUserPrefs

' === MODELMANAGER RELATIONSHIPS ===
ModelManager --> "1" AddressBook
ModelManager --> "1" UserPrefs

' === ADDRESSBOOK TO UNIQUE LISTS ===
AddressBook *--> "1" UniquePersonList
AddressBook *--> "1" UniqueEventList
AddressBook *--> "1" UniqueTodoList

' === UNIQUE LISTS TO ENTITIES ===
UniquePersonList --> "*" Person
UniqueEventList --> "*" Event
UniqueTodoList --> "*" Todo

' === MODELMANAGER FILTERED LISTS ===
ModelManager --> "*" Person : filteredPersons
ModelManager --> "*" Event : filteredEvents
ModelManager --> "*" Todo : filteredTodos

' === PERSON FIELD RELATIONSHIPS ===
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
Person *--> "1" Address
Person *--> "*" Tag
Person --> "0..1" EventAlias

' === EVENT FIELD RELATIONSHIPS ===
Event *--> "1" EventName
Event *--> "1" EventAlias

' === TODO FIELD RELATIONSHIPS ===
Todo *--> "1" TodoName
Todo --> "0..1" Name
@enduml
